### ISSUE TITLE
WebUI 不显示登录二维码

### ISSUE THREAD

**Issue by LogicDX342** [NapNeko/NapCat-Docker#27]
Log：
```text
/tmp/.X1-lock does not exist.
[preload] succeeded. /opt/QQ/resources/app/major.node
[preload] succeeded. /opt/QQ/resources/app/major.node
[12:0814/105622.911383:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[12:0814/105623.029867:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[12:0814/105623.029905:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[12:0814/105623.030725:ERROR:bus.cc(407)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[12:0814/105623.030762:ERROR:bus.cc(407)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[12:0814/105623.030773:ERROR:bus.cc(407)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[12:0814/105623.030823:ERROR:bus.cc(407)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[42:0814/105623.095087:ERROR:gl_surface_egl.cc(302)] No suitable EGL configs found.
[42:0814/105623.095197:ERROR:gl_context_egl.cc(160)] eglGetConfigAttrib failed with error EGL_BAD_CONFIG
[42:0814/105623.095328:ERROR:gl_surface_egl.cc(302)] No suitable EGL configs found.
[42:0814/105623.095434:ERROR:gl_surface_egl.cc(1040)] eglCreatePbufferSurface failed with error EGL_BAD_CONFIG
[42:0814/105623.095625:ERROR:gpu_info_collector.cc(86)] gl::GLContext::CreateOffscreenGLSurface failed
[42:0814/105623.095754:ERROR:gpu_info_collector.cc(584)] Could not create surface for info collection.
[42:0814/105623.095901:ERROR:gpu_init.cc(107)] CollectGraphicsInfo failed.
[42:0814/105623.097436:ERROR:viz_main_impl.cc(166)] Exiting GPU process due to errors during initialization
[67:0814/105623.190268:ERROR:gl_surface_egl.cc(302)] No suitable EGL configs found.
[67:0814/105623.190358:ERROR:gl_context_egl.cc(160)] eglGetConfigAttrib failed with error EGL_BAD_CONFIG
[67:0814/105623.190472:ERROR:gl_surface_egl.cc(302)] No suitable EGL configs found.
[67:0814/105623.190512:ERROR:gl_surface_egl.cc(1040)] eglCreatePbufferSurface failed with error EGL_BAD_CONFIG
[67:0814/105623.190548:ERROR:gpu_info_collector.cc(86)] gl::GLContext::CreateOffscreenGLSurface failed
[67:0814/105623.190580:ERROR:gpu_info_collector.cc(584)] Could not create surface for info collection.
[67:0814/105623.190613:ERROR:gpu_init.cc(107)] CollectGraphicsInfo failed.
[67:0814/105623.191927:ERROR:viz_main_impl.cc(166)] Exiting GPU process due to errors during initialization
NapCat Shell App Loading...
2024-08-14 10:56:23 [INFO] () | [NapCat] [WebUi] Current WebUi is running at http://0.0.0.0:6099 
2024-08-14 10:56:23 [INFO] () | [NapCat] [WebUi] Login URL is http://0.0.0.0:6099/webui 
2024-08-14 10:56:23 [INFO] () | [NapCat] [WebUi] Login Token is l4m0yo8e7gl 
2024-08-14 10:56:23 [ERROR] () | 快速登录失败，未找到该 QQ 历史登录记录，将使用二维码登录方式 
[103:0814/105623.306322:ERROR:gl_surface_egl.cc(302)] No suitable EGL configs found.
[103:0814/105623.306404:ERROR:gl_context_egl.cc(160)] eglGetConfigAttrib failed with error EGL_BAD_CONFIG
[103:0814/105623.306486:ERROR:gl_surface_egl.cc(302)] No suitable EGL configs found.
[103:0814/105623.306536:ERROR:gl_surface_egl.cc(1040)] eglCreatePbufferSurface failed with error EGL_BAD_CONFIG
[103:0814/105623.306593:ERROR:gpu_info_collector.cc(86)] gl::GLContext::CreateOffscreenGLSurface failed
[103:0814/105623.306632:ERROR:gpu_info_collector.cc(584)] Could not create surface for info collection.
[103:0814/105623.306691:ERROR:gpu_init.cc(107)] CollectGraphicsInfo failed.
[103:0814/105623.307630:ERROR:viz_main_impl.cc(166)] Exiting GPU process due to errors during initialization
```

docker-compose.yml:
```yaml
services:
    napcat:
        environment:
            - ACCOUNT=xxx
            - WSR_ENABLE=true
            - WS_URLS=["ws://127.0.0.1:8080/onebot/v11/ws"]
        container_name: napcat
        restart: always
        network_mode: bridge
        ports:
            - 6099:6099
        mac_address: 4F:C5:E9:97:92:40
        volumes:
            - /root/napcat/config:/usr/src/app/napcat/config
            - /root/napcat/qq-config:/root/.config
        image: mlikiowa/napcat-docker
```

镜像版本 v2.0.18
