### ISSUE TITLE
想问一下为什么我的 webUI 显示的 napcat 版本很低

### ISSUE THREAD

**Issue by iTofu** [NapNeko/NapCat-Docker#76]
docker-compose.yml:
```yml
services:
  gsuidcore:
    image: lilixxs666/gsuid-core:dev
    container_name: gsuidcore
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - GSCORE_HOST=${GSCORE_HOST}
    ports:
      - "8765:8765"
    volumes:
      - ./gscore_data:/gsuid_core/data
      - ./gscore_plugins:/gsuid_core/gsuid_core/plugins
    networks:
      - koishi_network

  napcat:
    image: mlikiowa/napcat-docker:latest
    container_name: napcat
    restart: unless-stopped
    environment:
      - NAPCAT_UID=${NAPCAT_UID}
      - NAPCAT_GID=${NAPCAT_GID}
      - MODE=${MODE}
      - WEBUI_TOKEN=${WEBUI_TOKEN}
      - ACCOUNT=${ACCOUNT}
    ports:
      - "6099:6099"
    volumes:
      - ./napcat:/app/napcat
      - ./ntqq:/app/.config/QQ
      - ./koishi:/koishi
    networks:
      - koishi_network
    mac_address: "02:42:ac:11:00:02"

  koishi:
    image: koishijs/koishi:latest
    container_name: koishi
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    ports:
      - "5140:5140"
    volumes:
      - ./napcat:/app/napcat
      - ./ntqq:/app/.config/QQ
      - ./koishi:/koishi
    networks:
      - koishi_network

networks:
  koishi_network:
    driver: bridge
```
image 是最新的：
```
docker inspect mlikiowa/napcat-docker:latest

        "RepoDigests": [
            "mlikiowa/napcat-docker@sha256:2829f842da60e7924846afd9c64e91b4c99f88e958e8eea15defb3537c6e35a0"
        ],
```
webUI 显示版本：
```
NapCat 版本 4.7.10
QQ 版本 3.2.17-34231
WebUI 版本 Next
系统版本 linux arm64 6.13.7-orbstack-00283-g9d1400e7e9c6
```
webUI 启动后的 Log:
```
[INFO] [QQ版本兼容性检测] 当前版本Appid未内置 通过Major获取 为了更好的性能请尝试更新NapCat
[INFO] [NapCat] [Core] NapCat.Core Version: 4.7.10
[INFO] [NapCat] [WebUi] WebUi Local Panel Url: http://127.0.0.1:6099/webui?token=xx
[INFO] 等待网络连接...
[INFO] 网络已连接
[INFO] 正在快速登录  xx
[ERROR] [Core] [Packet] PacketBackend 不支持当前QQ版本架构：3.2.17-34231-arm64，
            请参照 https://github.com/NapNeko/NapCatQQ/releases/tag/v4.7.10 配置正确的QQ版本！
[INFO] [Notice] [OneBot11] [network] 配置加载
WebSocket反向服务: ws://koishi:5140/onebot, : 已启动
```

跑在一台 mac mini m4 上。我的问题如下：
1. 为啥最新 image 跑起来后，webUI 显示 napcat 版本比较老（4.7.10），它和最新的 4.7.33 差挺远？
2. 看到 Log 有条 PacketBackend 相关的 Error，但我查 [文档](https://napneko.github.io/config/advanced#配置-packetbackend) 又说不用配置？
    > NapCat 3.6.0及以后的版本在Linux平台 (amd64, arm64), MacOS平台(amd64, arm64)，Windows平台 (amd64) 已内置 PacketBackend 实现 ，您无需进行额外的配置即可享受DLC的欢乐 (/≧▽≦)/
