### ISSUE TITLE
镜像的环境好像有问题

### ISSUE THREAD

**Issue by BiFangKNT** [NapNeko/NapCat-Docker#77]
compose 配置是按照官方示例的：
```
version: "3"
services:
    napcat:
        environment:
            - NAPCAT_UID=0
            - NAPCAT_GID=0
        ports:
            - 3002:3001
            - 6099:6099
        container_name: napcat
        network_mode: bridge
        restart: always
        image: mlikiowa/napcat-docker:latest
```

构建时一切正常，直到启动服务时：
`Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: \"bash\": executable file not found in $PATH: unknown`
